# ASSIGNMENT - 3 - HYPOTHESIS TESTING

In [1]:
#import the libraries
import pandas as pd
import numpy as np
import seaborn as sns

from scipy import stats
from scipy.stats import norm

import matplotlib.pyplot as plt
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

### Q.1A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units. A randomly selected sample of cutlets was collected from both units and measured? Analyze the data and draw inferences at 5% significance level. Please state the assumptions and tests that you carried out to check validity of the assumptions.



In [2]:
cutlets_data = pd.read_csv('Cutlets.csv')
cutlets_data.head(10)

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522
5  7.3871  6.8110
6  6.8755  7.2212
7  7.0621  6.6606
8  6.6840  7.2402
9  6.8236  7.0503

In [3]:
cutlets_data.shape

(35, 2)

In [4]:
# Assume Null hyposthesis as Ho: unit1 = unit2 = There is no difference in diameters of cutlets between two units
#Thus Alternate hypothesis as Ha: unit1!=unit2 (There is significant difference in diameters of cutlets between two units) 
#2 Sample 2 Tail test applicable

In [37]:
cutlets_unitA = pd.Series(cutlets_data.iloc[:,0])
cutlets_unitA.head(10)

0    6.8090
1    6.4376
2    6.9157
3    7.3012
4    7.4488
5    7.3871
6    6.8755
7    7.0621
8    6.6840
9    6.8236
Name: Unit A, dtype: float64

In [38]:
cutlets_unitB = pd.Series(cutlets_data.iloc[:,1])
cutlets_unitB.head(10)

0    6.7703
1    7.5093
2    6.7300
3    6.7878
4    7.1522
5    6.8110
6    7.2212
7    6.6606
8    7.2402
9    7.0503
Name: Unit B, dtype: float64

In [7]:
print(cutlets_unitA.mean())
print(cutlets_unitB.mean())

7.01909142857143
6.964297142857142


In [8]:
t_test,p_val = stats.ttest_ind(cutlets_unitA,cutlets_unitB)
t_test,p_val

(0.7228688704678063, 0.4722394724599501)

In [9]:
p_val #compare p_value with α = 0.05 (At 5% significance level)

0.4722394724599501

In [10]:
if p_val<0.05:
    print('We reject the null hypothesis saying that there is a significant difference in diameters of cutlets between two units.')
else:
    print('We do not reject the null hypothesis saying that there is no significant difference in diameters of cutlets between two units.')

We do not reject the null hypothesis saying that there is no significant difference in diameters of cutlets between two units.


In [11]:
# As (p_value=0.4722) > (α = 0.05); 
# Accept Null Hypothesis i.e. μ1 = μ2 ( Thus, there is no difference in diameters of cutlets between two units

### Q.2   A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) of reports of the laboratories on their preferred list. They collected a random sample and recorded TAT for reports of 4 laboratories. TAT is defined as sample collected to report dispatch.

### Analyze the data and determine whether there is any difference in average TAT among the different laboratories at 5% significance level.

In [12]:
hosp_lab = pd.read_csv('LabTAT.csv')
hosp_lab

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0          185.35        165.53        176.70        166.13
1          170.49        185.91        198.45        160.79
2          192.77        194.92        201.23        185.18
3          177.33        183.00        199.61        176.42
4          193.41        169.57        204.63        152.60
..            ...           ...           ...           ...
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

[120 rows x 4 columns]

In [13]:
hosp_lab1=pd.Series(hosp_lab.iloc[:,0])
hosp_lab1

0      185.35
1      170.49
2      192.77
3      177.33
4      193.41
        ...  
115    178.49
116    176.08
117    202.48
118    182.40
119    182.09
Name: Laboratory 1, Length: 120, dtype: float64

In [14]:
hosp_lab2=pd.Series(hosp_lab.iloc[:,1])
hosp_lab2

0      165.53
1      185.91
2      194.92
3      183.00
4      169.57
        ...  
115    170.66
116    183.98
117    174.54
118    197.18
119    215.17
Name: Laboratory 2, Length: 120, dtype: float64

In [15]:
hosp_lab3=pd.Series(hosp_lab.iloc[:,2])
hosp_lab3

0      176.70
1      198.45
2      201.23
3      199.61
4      204.63
        ...  
115    193.80
116    215.25
117    203.99
118    194.52
119    221.49
Name: Laboratory 3, Length: 120, dtype: float64

In [16]:
hosp_lab4=pd.Series(hosp_lab.iloc[:,3])
hosp_lab4

0      166.13
1      160.79
2      185.18
3      176.42
4      152.60
        ...  
115    172.68
116    177.64
117    170.27
118    150.87
119    162.21
Name: Laboratory 4, Length: 120, dtype: float64

In [17]:
print(hosp_lab1.mean())
print(hosp_lab2.mean())
print(hosp_lab3.mean())
print(hosp_lab4.mean())

178.36158333333339
178.9029166666668
199.91325000000003
163.6827499999999


In [18]:
p_value=stats.f_oneway(hosp_lab.iloc[:,0],hosp_lab.iloc[:,1],hosp_lab.iloc[:,2],hosp_lab.iloc[:,3])
p_value

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [19]:
p_value=stats.f_oneway(hosp_lab1,hosp_lab2,hosp_lab3,hosp_lab4)
p_value

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [20]:
#As p-value=0 < α = 0.05; Reject Null Hypothesis i.e. Atleast one sample TAT population mean is different 
#Thus there is variance or difference in average Turn Around Time (TAT) of reports of the laboratories on their preferred list

### Q.3.Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions.

In [21]:
buyer_ratio_data =pd.read_csv('BuyerRatio.csv')
buyer_ratio_data

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [22]:
buyer_ratio_gender = [[50,142,131,70],
                    [435,1523,1356,750]]
buyer_ratio_gender

[[50, 142, 131, 70], [435, 1523, 1356, 750]]

In [23]:
chi2_score,p_val,dof,expected_table = stats.chi2_contingency(observed=buyer_ratio_gender)
print('Chi-squared Value:',chi2_score)
print('P_Value:',p_val)
print('Degree of Freedom:',dof)
print('Expected Table:\n',expected_table)

Chi-squared Value: 1.595945538661058
P_Value: 0.6603094907091882
Degree of Freedom: 3
Expected Table:
 [[  42.76531299  146.81287862  131.11756787   72.30424052]
 [ 442.23468701 1518.18712138 1355.88243213  747.69575948]]


In [24]:
if p_val<0.05:
    print('We reject the null hypothesis saying that there is a significant difference in male and female buyer rations.')
else:
    print('We do not reject the null hypothesis saying that there is no significant difference in male and female buyer rations.')

We do not reject the null hypothesis saying that there is no significant difference in male and female buyer rations.


In [25]:
buyer_ratio_data.mean()

East     242.5
West     832.5
North    743.5
South    410.0
dtype: float64

In [26]:
stats.chi2_contingency([buyer_ratio_data["East"], 
                        buyer_ratio_data["West"], 
                        buyer_ratio_data["North"],
                        buyer_ratio_data["South"]])

(1.5959455386610577,
 0.6603094907091882,
 3,
 array([[  42.76531299,  442.23468701],
        [ 146.81287862, 1518.18712138],
        [ 131.11756787, 1355.88243213],
        [  72.30424052,  747.69575948]]))

In [27]:
if p_val<0.05:
    print('We reject the null hypothesis saying that there is a significant difference in male and female buyer rations across the regions.')
else:
    print('We do not reject the null hypothesis saying that there is no significant difference in male and female buyer rations across the regions.')

We do not reject the null hypothesis saying that there is no significant difference in male and female buyer rations across the regions.


### Q.4.TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms. Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether the defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences.

In [40]:
customer_order_form = pd.read_csv('Costomer+OrderForm.csv')
customer_order_form.head(5)

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [29]:
customer_order_form.shape

(300, 4)

In [30]:
customer_order_form.dtypes

Phillippines    object
Indonesia       object
Malta           object
India           object
dtype: object

In [31]:
customer_order_form.describe(include = 'all')

Phillippines   Indonesia       Malta       India
count           300         300         300         300
unique            2           2           2           2
top      Error Free  Error Free  Error Free  Error Free
freq            271         267         269         280

In [32]:
customer_order_form.value_counts()

Phillippines  Indonesia   Malta       India     
Error Free    Error Free  Error Free  Error Free    206
Defective     Error Free  Error Free  Error Free     21
Error Free    Defective   Error Free  Error Free     20
              Error Free  Defective   Error Free     18
                          Error Free  Defective      16
              Defective   Defective   Error Free      9
Defective     Error Free  Defective   Error Free      4
              Defective   Error Free  Error Free      2
              Error Free  Error Free  Defective       2
Error Free    Defective   Error Free  Defective       2
dtype: int64

In [33]:
Phillippines_value=customer_order_form['Phillippines'].value_counts()
Indonesia_value=customer_order_form['Indonesia'].value_counts()
Malta_value=customer_order_form['Malta'].value_counts()
India_value=customer_order_form['India'].value_counts()
print(Phillippines_value)
print(Indonesia_value)
print(Malta_value)
print(India_value)

Error Free    271
Defective      29
Name: Phillippines, dtype: int64
Error Free    267
Defective      33
Name: Indonesia, dtype: int64
Error Free    269
Defective      31
Name: Malta, dtype: int64
Error Free    280
Defective      20
Name: India, dtype: int64


In [34]:
stats.chi2_contingency([customer_order_form["Phillippines"].value_counts(),
                        customer_order_form["Indonesia"].value_counts(),
                        customer_order_form["Malta"].value_counts(),
                        customer_order_form["India"].value_counts()])

(3.8589606858203545,
 0.2771020991233144,
 3,
 array([[271.75,  28.25],
        [271.75,  28.25],
        [271.75,  28.25],
        [271.75,  28.25]]))

In [35]:
if p_val<0.05:
    print('We reject the null hypothesis saying that the defective percentage does varies signigicantly by center.')
else:
    print('We do not reject the null hypothesis saying that the defective percentage does not varies signigicantly by center.')

We do not reject the null hypothesis saying that the defective percentage does not varies signigicantly by center.
